### ISSUE TITLE
Developing steps not working in Windows Environment

### ISSUE THREAD

**Issue by satishreddy81** [mzabriskie/pdf-annotate.js#10]
Hi,

   Thank you so much for this library :+1:., Developing steps not working in windows environment. Could you please help how to solve this? here is errors i am getting :

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! pdf-annotate.js@0.0.0 start: `./scripts/web`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdf-annotate.js@0.0.0 start script './scripts/web'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pdf-annotate.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/web
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pdf-annotate.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pdf-annotate.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Satish\Favorites\Downloads\npm-master\pdf-annotate.js\npm-debug.log

**Comment by mzabriskie** [comment]
I suspect that this is due to my use of bash scripts. Probably ought to rewrite them to use node.

**Comment by geocine** [comment]
Checkout #24

**Comment by Gaurabp** [comment]
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\GAURAB\Desktop\pdf-annotate.js-master\server
'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
